=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Beskrivelse av datakvalitet
{fkbdatasett} inneholder data fra flere kilder (se kapittel 8 og 9). 

{fkbdatasett} er fremstilt vha. fjernmåling. Den dominerende datafangstmetoden for {fkbdatasett} er automatisk klassifisering av høyoppløslige satellittbilder fotogrammetrisk registrering.

Prinsippet er at fullstendighet prioriteres foran nøyaktighet og FKB-data for et område vil derfor bestå av data med varierende grad av kvalitet. Alle data er kodet med datafangstdato og posisjonskvalitet slik at det er mulig å vurdere datakvaliteten til det enkelte dataobjekt. Det vil også være mulig å aggregere denne informasjonen som finnes på objektnivå opp til en beskrivelse av kvaliteten på datainnholdet i området som helhet. Det er imidlertid vanskelig å garantere datakvaliteten for FKB innenfor et område.

=== Kvalitetskrav
==== Egenskapskonsistens
Klassifikasjonsriktighet skal være > 15 % feil klassifiserte egenskaper? Jf. F1-score i NIBIOs interne kvalitetskontroll av grønnstruktur for Drammen (95 %), Ullensvang (86 %) og Bodø (97 %). Her er jeg imidlertid usikker på hvorfor 400 punkter er valgt (200 i grønt områre, 200 i grått område), jf. tabell 5 i Geodatakvalitet.
Finner ingen informasjon om kontrollområder, kap. 7.2 i Geodatakvalitet.

==== Fullstendighet
Manglende objekter
Prosentandel manglende objekter?
Overskytende objekter
Prosentandel overskytende objekter?

==== Stedfestingsnøyaktighet
Krav til stedfestingsnøyaktighet settes etter FKB-standard C/D og nøyaktighetsklasse 4 Diffuse detaljer. Dette gir krav til systematiske avvik og standardavvik på 30 cm / 100 cm i grunnriss og 40 cm / 150 cm i høyde.
Er dette oppnåelig?

Er stedfestingsnøyaktighet i høyde aktuelt?
Kan/skal det brukes på sjikthøyder (m) (< 4, 4–8, 8–12, 12–16, > 16)?
Hva med felt-, busk- og tresjikt (m)? Senke kravet til 100 cm i høyde siden klasseinndelinga er <1, 1-3, >3?

