=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Beskrivelse av datakvalitet
{fkbdatasett} inneholder data fra flere kilder (se kapittel 8 og 9 i denne spesisfikasjonen). 

{fkbdatasett} er fremstilt vha. fjernmåling. Den dominerende datafangstmetoden for {fkbdatasett} er automatisk klassifisering av høyoppløslige satellittbilder fotogrammetrisk registrering.

For å få et godt bilde av kvaliteten til data innenfor et område må man derfor vurdere datakvaliteten (metadata) til kartobjektene. Det vil også være mulig å aggregere denne informasjonen som finnes på objektnivå opp til en beskrivelse av kvaliteten på datainnholdet i området som helhet. Det er imidlertid vanskelig å garantere datakvaliteten for FKB innenfor et område. Slik det står i  FKB-AR5.
Prinsippet er at fullstendighet prioriteres foran nøyaktighet og FKB-data for et område vil derfor bestå av data med varierende grad av kvalitet. Alle data er kodet med datafangstdato og posisjonskvalitet slik at det er mulig å vurdere datakvaliteten til det enkelte dataobjekt. Det vil også være mulig å aggregere denne informasjonen som finnes på objektnivå opp til en beskrivelse av kvaliteten på datainnholdet i området som helhet. Det er imidlertid vanskelig å garantere datakvaliteten for FKB innenfor et område. Slik det står i FKB-Arealbruk.

=== Kvalitetskrav (Jeg har tatt utgangspunkt i kap. 8 Kvalitet i FKB Generell del)
==== Egenskapskonsistens
Klassifikasjonsriktighet skal være <15 % feil klassifiserte egenskaper. Hva menes her med egenskaper? Er det f.eks. hoyde, ndvi, andelbunn, andelbusk og andeltre for objekttypen Bunn? Eller er det feilklassifiserte objekttyper? Klassifisert som bunn, menn skulle vært busk?
Jf. F1-score i NIBIOs interne kvalitetskontroll av grønnstruktur for Drammen (95 %), Ullensvang (86 %) og Bodø (97 %). Her er jeg imidlertid usikker på hvorfor 400 punkter er valgt (~200 i grønt område, ~200 i grått område), jf. tabell 4 i kap. 7.4.1. Geodatakvalitet.
Finner ingen informasjon om kontrollområder, kap. 7.2 i Geodatakvalitet.

==== Fullstendighet
Manglende objekter
Prosentandel manglende objekter? Er det realistisk å telle opp manglende trær, grøntområder,…? Bygninger vil jo visuelt mangle ettersom det er ønskelig at trekroner høyere enn bygninger ikke skal klippes mot bygninger.
Overskytende objekter
Prosentandel overskytende objekter? Jf. manglende.

==== Stedfestingsnøyaktighet
Krav til stedfestingsnøyaktighet settes etter FKB-standard C/D og nøyaktighetsklasse 4 Diffuse detaljer. Dette gir krav til systematiske avvik og standardavvik på 30 cm / 100 cm i grunnriss og 40 cm / 150 cm i høyde.

Er dette oppnåelig?
Er stedfestingsnøyaktighet i høyde aktuelt?
Kan/skal det brukes på sjikthøyder (m) (< 4, 4–8, 8–12, 12–16, > 16)?
Hva med felt-, busk- og tresjikt (m)? Senke kravet til 100 cm eller mindre i høyde siden klasseinndelinga er <1, 1-3, >3?
